services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: crudasistencialmaqueta
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - ./crud_asistencial:/app
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - TZ=America/Santiago
    command: ["./wait-for-it.sh", "db:5432", "--", "gunicorn", "--bind", "0.0.0.0:8000", "crud_asistencial.wsgi:application"]

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}   # Usando variable DB_USERNAME
      POSTGRES_PASSWORD: ${DB_PASSWORD}   # Usando variable DB_PASSWORD
      POSTGRES_DB: ${DB_NAME}  # Usando variable DB_NAME
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
