# Generated by Django 4.2.16 on 2024-11-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='codigo_pais',
            new_name='codigo_telefonico_pais',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='codigo_region',
            new_name='codigo_telefonico_region',
        ),
    ]
