# Generated by Django 4.2.16 on 2024-11-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0002_rename_codigo_pais_pais_codigo_telefonico_pais_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
    ]
