# Generated by Django 4.2.16 on 2024-11-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades', '0003_alter_ciudad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codigo_telefonico_pais',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='codigo_telefonico_region',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
