# Generated by Django 4.2.16 on 2024-11-23 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalDeSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Persona', max_length=100)),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone_number', models.CharField(blank=True, default='+56900000000', max_length=12)),
                ('specialty', models.CharField(db_index=True, max_length=100)),
                ('medic_rol_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
                ('place_of_origin', models.ForeignKey(blank=True, help_text='Lugar de procedencia, si la persona no es originaria de esta region o provincia donde desempeña sus labores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healtcare_professioals_origin', to='locations.address')),
            ],
            options={
                'verbose_name': 'Profesional de la salud',
                'verbose_name_plural': 'Profesionales de la salud',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Persona', max_length=100)),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone_number', models.CharField(blank=True, default='+56900000000', max_length=12)),
                ('medical_record_number', models.CharField(max_length=20, unique=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Persona', max_length=100)),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone_number', models.CharField(blank=True, default='+56900000000', max_length=12)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.address')),
            ],
            options={
                'verbose_name': 'Empleados',
            },
        ),
    ]
