# Generated by Django 4.2.16 on 2024-11-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionaldesalud',
            name='place_of_origin',
            field=models.ForeignKey(blank=True, help_text='Lugar de procedencia, si la persona no es originaria de esta region o provincia donde desempeña sus labores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales_salud_origen', to='locations.address'),
        ),
    ]
