# Generated by Django 4.2.16 on 2024-11-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0003_alter_employee_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="father_lastname",
            field=models.CharField(default="Apellido paterno", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="mother_lastname",
            field=models.CharField(default="Apellido materno", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="father_lastname",
            field=models.CharField(default="Apellido paterno", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="mother_lastname",
            field=models.CharField(default="Apellido materno", max_length=100),
        ),
        migrations.AddField(
            model_name="profesionaldesalud",
            name="father_lastname",
            field=models.CharField(default="Apellido paterno", max_length=100),
        ),
        migrations.AddField(
            model_name="profesionaldesalud",
            name="mother_lastname",
            field=models.CharField(default="Apellido materno", max_length=100),
        ),
    ]
